### PR TITLE
End of models

### PR DESCRIPTION
**Pull request by heiskr**

### CODE REVIEW

**Comment by Saifanl** [comment]
Screenshot_2022-06-15-03-08-06-55_439a3fec0400f8974d35eed09a31f914

**Comment by Saifanl** [comment]
Peugeot Porsche design

**Comment by 946054** [comment]
ولا اروع مدهش

**Review by Jackpoot778 — COMMENTED** [review]
Go

**Review by Emisio1 — COMMENTED** [review]
server/routes/card.py

**Comment by Emisio1** [comment]
> server/routes/card.py

**Pull request merged**
